"""Static object family legend descriptors for Leonardo V2.

This module defines canonical `ObjectFamilyLegend` values for current V2
families and conservative placeholders for future families. The legends are
static descriptors only. They do not discover objects, register providers,
mutate runtime state, implement Object Map behavior, or call domain services.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from leonardo.contracts.downloads import CONNECTION_DOWNLOAD_MANAGER_OWNER_DOMAIN
from leonardo.contracts.traceable_object import ObjectFamilyLegend


CURRENT_V2_FAMILY_IDS: tuple[str, ...] = (
    "app_runtime",
    "session",
    "service",
    "task",
    "operation",
    "process",
    "connection",
    "websocket_channel",
    "window",
    "action",
    "contract_descriptor",
    "audit_event",
    "error_report",
    "download_request",
    "download_preflight",
    "download_item",
    "download_execution_snapshot",
    "download_capability",
)

FUTURE_PLACEHOLDER_FAMILY_IDS: tuple[str, ...] = (
    "study",
    "study_environment",
    "chart_session",
    "chart_panel",
    "workspace_snapshot",
    "notebook",
    "artifact_recipe",
    "recipe_collection",
    "saved_artifact",
    "artifact_metadata",
    "artifact_collection",
    "analysis_database",
    "analysis_project",
    "analysis_run",
    "analysis_report",
    "saved_rule_package",
    "validation_scenario",
    "trading_signal",
    "trading_strategy",
    "order_intent",
    "provider_session",
    "websocket_subscription",
    "websocket_message_trace",
)

_LEGEND_DOC = "docs/contracts_docs/OBJECT_FAMILY_LEGENDS.md"
_TRACEABLE_DOC = "docs/contracts_docs/TRACEABLE_OBJECTS.md"
_LEGEND_TEST = "tests/contracts_test/test_object_family_legends.py"

_CORE_READ_PROVIDER = "current owner read model plus future read-only Object Map"
_FUTURE_READ_PROVIDER = "future read-only Object Map after domain owner exists"


def _current_legend(
    family_id: str,
    *,
    owner_domain: str,
    owner_component: str,
    mutation_owner: str,
    read_provider: str,
    runtime_or_persistent: str,
    truth_source: str,
    required_identity_fields: tuple[str, ...],
    optional_identity_fields: tuple[str, ...] = (),
    metadata_fields: tuple[str, ...] = (),
    lifecycle_statuses: tuple[str, ...] = (),
    allowed_actions: tuple[str, ...] = (),
    permission_refs: tuple[str, ...] = (),
    audit_event_types: tuple[str, ...] = (),
    relationships_in: tuple[str, ...] = (),
    relationships_out: tuple[str, ...] = (),
    related_contracts: tuple[str, ...] = (),
    related_docs: tuple[str, ...] = (),
    related_tests: tuple[str, ...] = (),
    extra: Mapping[str, object] | None = None,
) -> ObjectFamilyLegend:
    return _legend(
        family_id,
        owner_domain=owner_domain,
        owner_component=owner_component,
        mutation_owner=mutation_owner,
        read_provider=read_provider,
        runtime_or_persistent=runtime_or_persistent,
        truth_source=truth_source,
        required_identity_fields=required_identity_fields,
        optional_identity_fields=optional_identity_fields,
        metadata_fields=metadata_fields,
        lifecycle_statuses=lifecycle_statuses,
        allowed_actions=allowed_actions or ("inspect",),
        permission_refs=permission_refs,
        audit_event_types=audit_event_types,
        relationships_in=relationships_in,
        relationships_out=relationships_out,
        related_contracts=related_contracts,
        related_docs=(_TRACEABLE_DOC, _LEGEND_DOC, *related_docs),
        related_tests=(_LEGEND_TEST, *related_tests),
        extra={"status": "current_v2", **dict(extra or {})},
    )


def _download_legend(
    family_id: str,
    *,
    owner_component: str,
    mutation_owner: str,
    truth_source: str,
    required_identity_fields: tuple[str, ...],
    metadata_fields: tuple[str, ...],
    lifecycle_statuses: tuple[str, ...],
    audit_event_types: tuple[str, ...],
    relationships_in: tuple[str, ...] = (),
    relationships_out: tuple[str, ...] = (),
    related_contracts: tuple[str, ...] = (),
    related_tests: tuple[str, ...] = (),
) -> ObjectFamilyLegend:
    return _current_legend(
        family_id,
        owner_domain=CONNECTION_DOWNLOAD_MANAGER_OWNER_DOMAIN,
        owner_component=owner_component,
        mutation_owner=mutation_owner,
        read_provider="download read models and future read-only Object Map",
        runtime_or_persistent="runtime",
        truth_source=truth_source,
        required_identity_fields=required_identity_fields,
        metadata_fields=metadata_fields,
        lifecycle_statuses=lifecycle_statuses,
        allowed_actions=("inspect",),
        permission_refs=("download:view",),
        audit_event_types=audit_event_types,
        relationships_in=relationships_in,
        relationships_out=relationships_out,
        related_contracts=related_contracts,
        related_docs=("docs/contracts_docs/DOWNLOAD_EXECUTION_CONTRACTS.md",),
        related_tests=related_tests,
        extra={
            "read_model_only": True,
            "forbidden_behavior": ("execution", "adapters", "storage_writers"),
        },
    )


def _future_legend(
    family_id: str,
    *,
    owner_domain: str,
    owner_component: str,
    runtime_or_persistent: str,
    required_identity_fields: tuple[str, ...],
    metadata_fields: tuple[str, ...],
    relationships_in: tuple[str, ...] = (),
    relationships_out: tuple[str, ...] = (),
) -> ObjectFamilyLegend:
    return _legend(
        family_id,
        owner_domain=owner_domain,
        owner_component=owner_component,
        mutation_owner=f"{owner_component} (not implemented)",
        read_provider=_FUTURE_READ_PROVIDER,
        runtime_or_persistent=runtime_or_persistent,
        truth_source="future domain owner; no active V2 implementation",
        required_identity_fields=required_identity_fields,
        metadata_fields=metadata_fields,
        lifecycle_statuses=("planned",),
        allowed_actions=("inspect",),
        permission_refs=_future_permissions(owner_domain),
        audit_event_types=(),
        relationships_in=relationships_in,
        relationships_out=relationships_out,
        related_docs=(_TRACEABLE_DOC, _LEGEND_DOC),
        related_tests=(_LEGEND_TEST,),
        extra={
            "status": "future",
            "placeholder": True,
            "domain_owner_required": True,
            "implementation_not_started": True,
        },
    )


def _legend(
    family_id: str,
    *,
    owner_domain: str,
    owner_component: str,
    mutation_owner: str,
    read_provider: str,
    runtime_or_persistent: str,
    truth_source: str,
    required_identity_fields: tuple[str, ...],
    optional_identity_fields: tuple[str, ...] = (),
    metadata_fields: tuple[str, ...] = (),
    lifecycle_statuses: tuple[str, ...] = (),
    allowed_actions: tuple[str, ...] = (),
    permission_refs: tuple[str, ...] = (),
    audit_event_types: tuple[str, ...] = (),
    relationships_in: tuple[str, ...] = (),
    relationships_out: tuple[str, ...] = (),
    related_contracts: tuple[str, ...] = (),
    related_docs: tuple[str, ...] = (),
    related_tests: tuple[str, ...] = (),
    extra: Mapping[str, object] | None = None,
) -> ObjectFamilyLegend:
    return ObjectFamilyLegend(
        family_id=family_id,
        object_kind=family_id,
        owner_domain=owner_domain,
        owner_component=owner_component,
        mutation_owner=mutation_owner,
        read_provider=read_provider,
        runtime_or_persistent=runtime_or_persistent,
        truth_source=truth_source,
        required_identity_fields=required_identity_fields,
        optional_identity_fields=optional_identity_fields,
        metadata_fields=metadata_fields,
        lifecycle_statuses=lifecycle_statuses,
        allowed_actions=allowed_actions,
        permission_refs=permission_refs,
        audit_event_types=audit_event_types,
        relationships_in=relationships_in,
        relationships_out=relationships_out,
        related_contracts=related_contracts,
        related_docs=related_docs,
        related_tests=related_tests,
        extra=extra or {},
    )


def _future_permissions(owner_domain: str) -> tuple[str, ...]:
    if owner_domain.startswith("research"):
        return ("research:view",)
    if owner_domain.startswith("data_manager"):
        return ("data_manager:view",)
    if owner_domain.startswith("analysis"):
        return ("analysis:view",)
    if owner_domain.startswith("trading"):
        return ("trading:view",)
    if owner_domain.startswith("provider") or owner_domain.startswith("core.connection"):
        return ("connection:view",)
    return ("runtime:view",)


OBJECT_FAMILY_LEGENDS: tuple[ObjectFamilyLegend, ...] = (
    _current_legend(
        "app_runtime",
        owner_domain="core",
        owner_component="LeonardoApp",
        mutation_owner="LeonardoApp lifecycle and StateStore app runtime state",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="StateStore app runtime state and AuditLog lifecycle events",
        required_identity_fields=("app_id",),
        metadata_fields=("status", "last_updated_utc"),
        lifecycle_statuses=("initialized", "starting", "running", "stopping", "stopped"),
        allowed_actions=("inspect",),
        permission_refs=("runtime:view",),
        audit_event_types=("app.lifecycle", "app.started", "app.stopped"),
        relationships_out=("owns", "references"),
        related_contracts=("leonardo.runtime.app_state",),
        related_docs=("docs/core_docs/CORE_RUNTIME_FOUNDATION.md",),
        related_tests=("tests/core_test/test_app_runtime_foundation.py",),
    ),
    _current_legend(
        "session",
        owner_domain="core",
        owner_component="SessionManager",
        mutation_owner="SessionManager",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="SessionManager current session and AuditLog session events",
        required_identity_fields=("session_id",),
        metadata_fields=("actor_id", "origin", "started_at_utc"),
        lifecycle_statuses=("active", "ended"),
        allowed_actions=("inspect",),
        permission_refs=("runtime:view",),
        audit_event_types=("session.started", "session.ended"),
        relationships_out=("owns", "references"),
        related_contracts=("leonardo.identity.session_context",),
        related_docs=("docs/contracts_docs/PERMISSION_MATRIX.md",),
        related_tests=("tests/core_test/test_session_and_user_policy.py",),
    ),
    _current_legend(
        "service",
        owner_domain="core",
        owner_component="ServiceRegistry",
        mutation_owner="ServiceRegistry and LeonardoApp lifecycle",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="ServiceRegistry descriptors and StateStore service runtime state",
        required_identity_fields=("service_id",),
        metadata_fields=("kind", "status", "last_updated_utc"),
        lifecycle_statuses=("registered", "starting", "running", "stopping", "stopped"),
        allowed_actions=("inspect",),
        permission_refs=("service:view",),
        audit_event_types=("service.registered", "service.state_changed"),
        relationships_in=("owned_by", "depends_on"),
        relationships_out=("depends_on", "references"),
        related_contracts=(
            "leonardo.services.service_descriptor",
            "leonardo.runtime.service_state",
        ),
        related_docs=("docs/core_docs/CORE_RUNTIME_FOUNDATION.md",),
        related_tests=("tests/core_test/test_service_registry.py",),
    ),
    _current_legend(
        "task",
        owner_domain="core",
        owner_component="TaskManager",
        mutation_owner="TaskManager",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="TaskManager and StateStore task runtime state",
        required_identity_fields=("task_id",),
        metadata_fields=("task_name", "status", "operation_id", "correlation_id"),
        lifecycle_statuses=("active", "completed", "failed", "cancelled"),
        allowed_actions=("inspect",),
        permission_refs=("task:view",),
        audit_event_types=("task.created", "task.completed", "task.failed", "task.cancelled"),
        relationships_in=("schedules_task", "created_by"),
        relationships_out=("depends_on", "references"),
        related_contracts=("leonardo.runtime.task_state",),
        related_docs=("docs/core_docs/CORE_ASYNC_TASK_MANAGER.md",),
        related_tests=("tests/core_test/test_task_manager.py",),
    ),
    _current_legend(
        "operation",
        owner_domain="core",
        owner_component="OperationRegistry",
        mutation_owner="OperationRegistry",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="OperationRegistry and StateStore operation runtime state",
        required_identity_fields=("operation_id",),
        metadata_fields=("operation_kind", "status", "label", "task_id", "action_id"),
        lifecycle_statuses=("requested", "running", "completed", "failed", "cancelled"),
        allowed_actions=("inspect",),
        permission_refs=("operation:view",),
        audit_event_types=("operation.created", "operation.running", "operation.completed"),
        relationships_in=("creates_operation",),
        relationships_out=("schedules_task", "uses_connection", "references"),
        related_contracts=("leonardo.operations.operation_state",),
        related_docs=("docs/contracts_docs/OPERATION_RUNTIME_CONTRACTS.md",),
        related_tests=("tests/core_test/test_operation_registry.py",),
    ),
    _current_legend(
        "process",
        owner_domain="core",
        owner_component="ProcessManager",
        mutation_owner="ProcessManager",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="ProcessManager and StateStore process runtime state",
        required_identity_fields=("process_id",),
        metadata_fields=("label", "kind", "status", "pid", "operation_id", "task_id"),
        lifecycle_statuses=("registered", "starting", "running", "exited", "failed"),
        allowed_actions=("inspect",),
        permission_refs=("process:view",),
        audit_event_types=("process.registered", "process.started", "process.exited"),
        relationships_in=("creates_operation", "schedules_task"),
        relationships_out=("references",),
        related_contracts=(
            "leonardo.processes.launch_request",
            "leonardo.processes.runtime_state",
        ),
        related_docs=("docs/core_docs/CORE_PROCESS_MANAGER.md",),
        related_tests=("tests/core_test/test_process_manager.py",),
    ),
    _current_legend(
        "connection",
        owner_domain="core.connection",
        owner_component="ConnectionRegistry",
        mutation_owner="ConnectionRegistry",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="ConnectionRegistry and StateStore connection runtime state",
        required_identity_fields=("connection_id",),
        metadata_fields=("label", "kind", "protocol", "direction", "status"),
        lifecycle_statuses=("registered", "connecting", "connected", "disconnected", "failed"),
        allowed_actions=("inspect",),
        permission_refs=("connection:view",),
        audit_event_types=("connection.registered", "connection.status_changed"),
        relationships_in=("uses_connection",),
        relationships_out=("owns_channel", "references"),
        related_contracts=(
            "leonardo.connections.definition",
            "leonardo.connections.runtime_state",
        ),
        related_docs=("docs/core_docs/CORE_CONNECTION_TRACKING.md",),
        related_tests=("tests/core_test/test_connection_registry.py",),
        extra={
            "forbidden_behavior": ("provider_client_implementation", "live_transport"),
        },
    ),
    _current_legend(
        "websocket_channel",
        owner_domain="core.connection",
        owner_component="ConnectionRegistry",
        mutation_owner="ConnectionRegistry",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="ConnectionRegistry and StateStore websocket channel runtime state",
        required_identity_fields=("channel_id", "connection_id"),
        metadata_fields=("label", "status", "messages_sent", "messages_received"),
        lifecycle_statuses=("registered", "subscribed", "active", "closed", "failed"),
        allowed_actions=("inspect",),
        permission_refs=("connection:view",),
        audit_event_types=("websocket_channel.registered", "websocket_channel.status_changed"),
        relationships_in=("owns_channel",),
        relationships_out=("owns", "references"),
        related_contracts=(
            "leonardo.connections.websocket_channel_definition",
            "leonardo.connections.websocket_channel_runtime_state",
        ),
        related_docs=("docs/core_docs/CORE_CONNECTION_TRACKING.md",),
        related_tests=("tests/core_test/test_connection_registry.py",),
        extra={
            "forbidden_behavior": ("websocket_client_implementation", "message_transport"),
        },
    ),
    _current_legend(
        "window",
        owner_domain="gui",
        owner_component="GUI metadata and WindowRegistry",
        mutation_owner="GUI metadata/settings owner for static metadata; WindowRegistry for runtime state",
        read_provider="GUI metadata, WindowRegistry runtime state, and future read-only Object Map",
        runtime_or_persistent="hybrid",
        truth_source="GUI metadata TOML plus StateStore window runtime state",
        required_identity_fields=("window_id", "metadata_id", "object_name"),
        optional_identity_fields=("test_id",),
        metadata_fields=("title", "label", "geometry_policy", "instance_policy"),
        lifecycle_statuses=("registered", "visible", "focused", "close_requested", "closed"),
        allowed_actions=("inspect",),
        permission_refs=("runtime:view",),
        audit_event_types=("gui.window.registered", "gui.window.opened", "gui.window.closed"),
        relationships_in=("references",),
        relationships_out=("owns", "triggers", "affected_by_settings"),
        related_contracts=("leonardo.gui.window_definition",),
        related_docs=("docs/contracts_docs/GUI_OBSERVABILITY_CONTRACTS.md",),
        related_tests=("tests/core_test/test_window_registry.py",),
        extra={"forbidden_behavior": ("domain_execution", "permission_policy")},
    ),
    _current_legend(
        "action",
        owner_domain="gui.core",
        owner_component="ActionRegistry and GuiActionObserver",
        mutation_owner="ActionRegistry for definitions and trigger records",
        read_provider="ActionRegistry recent triggers and future read-only Object Map",
        runtime_or_persistent="hybrid",
        truth_source="GUI metadata/action definitions plus StateStore action trigger records",
        required_identity_fields=("action_id", "window_id"),
        optional_identity_fields=("required_permissions",),
        metadata_fields=("label", "kind", "is_placeholder"),
        lifecycle_statuses=("registered", "observed", "denied"),
        allowed_actions=("inspect",),
        permission_refs=("runtime:view", "settings:manage", "gui_settings:manage"),
        audit_event_types=("gui.action.triggered", "gui.action.denied"),
        relationships_in=("owns", "references"),
        relationships_out=("triggers", "creates_operation", "references"),
        related_contracts=("leonardo.gui.action_definition",),
        related_docs=("docs/contracts_docs/GUI_OBSERVABILITY_CONTRACTS.md",),
        related_tests=("tests/gui_test/test_gui_action_tracking.py",),
        extra={"forbidden_behavior": ("execution", "domain_validation")},
    ),
    _current_legend(
        "contract_descriptor",
        owner_domain="core.contracts",
        owner_component="ContractRegistry",
        mutation_owner="ContractRegistry",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="static_metadata",
        truth_source="ContractRegistry registered descriptors",
        required_identity_fields=("contract_id", "version"),
        metadata_fields=("owner", "status", "schema_kind", "required_fields"),
        lifecycle_statuses=("draft", "active", "deprecated", "retired"),
        allowed_actions=("inspect", "validate_payload"),
        permission_refs=("runtime:view",),
        audit_event_types=("contract.registered", "contract.validation_failed"),
        relationships_out=("references", "depends_on"),
        related_contracts=("leonardo.contracts.kernel.ContractDescriptor",),
        related_docs=(
            "docs/contracts_docs/CONTRACT_KERNEL.md",
            "docs/core_docs/CORE_CONTRACT_REGISTRY.md",
        ),
        related_tests=("tests/core_test/test_contract_registry.py",),
    ),
    _current_legend(
        "audit_event",
        owner_domain="core.audit",
        owner_component="AuditLog",
        mutation_owner="AuditLog",
        read_provider="AuditLog sinks, bounded previews, and future read-only Object Map",
        runtime_or_persistent="hybrid",
        truth_source="AuditLog historical event stream",
        required_identity_fields=("event_id",),
        metadata_fields=("event_type", "severity", "category", "timestamp_utc"),
        lifecycle_statuses=("recorded", "sink_failed"),
        allowed_actions=("inspect",),
        permission_refs=("audit:view",),
        audit_event_types=("audit.event_recorded", "audit.sink_failed"),
        relationships_in=("references",),
        relationships_out=("references",),
        related_contracts=("leonardo.audit.event",),
        related_docs=("docs/contracts_docs/AUDIT_EVENT_CONTRACTS.md",),
        related_tests=("tests/core_test/test_audit_log.py",),
    ),
    _current_legend(
        "error_report",
        owner_domain="core.errors",
        owner_component="ErrorRouter",
        mutation_owner="ErrorRouter",
        read_provider=_CORE_READ_PROVIDER,
        runtime_or_persistent="runtime",
        truth_source="ErrorRouter reports and AuditLog error events",
        required_identity_fields=("error_id",),
        metadata_fields=("severity", "message", "timestamp_utc", "context"),
        lifecycle_statuses=("reported", "routed"),
        allowed_actions=("inspect",),
        permission_refs=("error:view",),
        audit_event_types=("error.reported", "error.routed"),
        relationships_in=("references",),
        relationships_out=("references",),
        related_contracts=("leonardo.errors.error_report",),
        related_docs=("docs/contracts_docs/RUNTIME_KERNEL_CONTRACTS.md",),
        related_tests=("tests/core_test/test_error_router.py",),
    ),
    _download_legend(
        "download_request",
        owner_component="DownloadManager",
        mutation_owner="DownloadManager request read-model store",
        truth_source="DownloadManager in-memory request read models",
        required_identity_fields=("request_id",),
        metadata_fields=("workflow_kind", "source", "market", "status", "timeframes"),
        lifecycle_statuses=("drafted", "submitted", "validated", "failed", "cancelled"),
        audit_event_types=("download.request.submitted", "download.request.validated"),
        relationships_out=("creates_item", "creates_plan", "uses_connection"),
        related_contracts=("leonardo.downloads.request",),
        related_tests=("tests/core_test/test_download_manager.py",),
    ),
    _download_legend(
        "download_preflight",
        owner_component="DownloadManager",
        mutation_owner="DownloadManager preflight read-model store",
        truth_source="DownloadManager structural preflight read models",
        required_identity_fields=("request_id",),
        metadata_fields=("status", "can_run", "issues", "required_connections"),
        lifecycle_statuses=("not_run", "passed", "warning", "failed", "blocked"),
        audit_event_types=("download.preflight.created", "download.preflight.failed"),
        relationships_in=("references",),
        relationships_out=("validates", "uses_connection"),
        related_contracts=("leonardo.downloads.preflight",),
        related_tests=("tests/core_test/test_download_manager.py",),
    ),
    _download_legend(
        "download_item",
        owner_component="DownloadManager",
        mutation_owner="DownloadManager item read-model store",
        truth_source="DownloadManager item read models",
        required_identity_fields=("item_id", "request_id"),
        metadata_fields=("symbol", "timeframe", "status", "connection_id", "channel_id"),
        lifecycle_statuses=("queued", "running", "completed", "failed", "skipped"),
        audit_event_types=("download.item.created", "download.item.updated"),
        relationships_in=("creates_item",),
        relationships_out=("uses_connection", "owns_channel", "writes_dataset"),
        related_contracts=("leonardo.downloads.request_item",),
        related_tests=("tests/core_test/test_download_manager.py",),
    ),
    _download_legend(
        "download_execution_snapshot",
        owner_component="DownloadExecutionManager",
        mutation_owner="DownloadExecutionManager snapshot read-model store",
        truth_source="DownloadExecutionManager non-executing snapshot read models",
        required_identity_fields=("plan_id", "request_id"),
        metadata_fields=("phase", "progress", "preflight_layers", "estimate", "errors"),
        lifecycle_statuses=("planned", "ready", "blocked", "completed", "failed", "cancelled"),
        audit_event_types=("download_execution.plan_created", "download_execution.phase_changed"),
        relationships_in=("creates_plan",),
        relationships_out=("references", "writes_dataset"),
        related_contracts=("leonardo.download_execution.snapshot",),
        related_tests=("tests/core_test/test_download_execution_manager.py",),
    ),
    _download_legend(
        "download_capability",
        owner_component="DownloadCapabilityCatalog",
        mutation_owner="DownloadCapabilityCatalog static capability store",
        truth_source="DownloadCapabilityCatalog static provider capability facts",
        required_identity_fields=("provider",),
        metadata_fields=("markets", "data_kinds", "timeframes", "transports"),
        lifecycle_statuses=("declared", "supported", "unsupported", "deprecated"),
        audit_event_types=("download_capability.registered",),
        relationships_in=("references",),
        relationships_out=("validates", "references"),
        related_contracts=("leonardo.download_provider_capabilities.provider",),
        related_tests=("tests/core_test/test_download_capability_catalog.py",),
    ),
    _future_legend(
        "study",
        owner_domain="research",
        owner_component="future study owner",
        runtime_or_persistent="hybrid",
        required_identity_fields=("study_id",),
        metadata_fields=("study_type", "inputs", "parameters", "style"),
        relationships_in=("references",),
        relationships_out=("derives_from", "produces_artifact"),
    ),
    _future_legend(
        "study_environment",
        owner_domain="research",
        owner_component="future study environment owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("study_environment_id",),
        metadata_fields=("dataset_refs", "study_refs", "recipe_refs"),
        relationships_out=("owns", "derives_from", "creates_plan"),
    ),
    _future_legend(
        "chart_session",
        owner_domain="gui.chart",
        owner_component="future chart session owner",
        runtime_or_persistent="hybrid",
        required_identity_fields=("chart_session_id",),
        metadata_fields=("workspace_ref", "dataset_ref", "viewport"),
        relationships_out=("owns", "references"),
    ),
    _future_legend(
        "chart_panel",
        owner_domain="gui.chart",
        owner_component="future chart panel owner",
        runtime_or_persistent="runtime",
        required_identity_fields=("chart_panel_id", "chart_session_id"),
        metadata_fields=("pane_role", "series_refs", "study_refs"),
        relationships_in=("owns",),
        relationships_out=("references",),
    ),
    _future_legend(
        "workspace_snapshot",
        owner_domain="gui.workspace",
        owner_component="future workspace snapshot owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("workspace_snapshot_id",),
        metadata_fields=("window_refs", "chart_session_refs", "settings_refs"),
        relationships_out=("owns", "references"),
    ),
    _future_legend(
        "notebook",
        owner_domain="research",
        owner_component="future notebook owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("notebook_id",),
        metadata_fields=("cells", "artifact_refs", "analysis_refs"),
        relationships_out=("references", "produces_report"),
    ),
    _future_legend(
        "artifact_recipe",
        owner_domain="data_manager",
        owner_component="future artifact recipe owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("recipe_id",),
        metadata_fields=("inputs", "parameters", "output_contract"),
        relationships_in=("derives_from",),
        relationships_out=("produces_artifact", "depends_on"),
    ),
    _future_legend(
        "recipe_collection",
        owner_domain="data_manager",
        owner_component="future recipe collection owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("recipe_collection_id",),
        metadata_fields=("recipe_refs", "selection_policy"),
        relationships_out=("owns", "references"),
    ),
    _future_legend(
        "saved_artifact",
        owner_domain="data_manager",
        owner_component="future artifact store owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("artifact_id",),
        metadata_fields=("artifact_type", "storage_ref", "quality_status"),
        relationships_in=("produces_artifact",),
        relationships_out=("references", "derives_from"),
    ),
    _future_legend(
        "artifact_metadata",
        owner_domain="data_manager",
        owner_component="future artifact metadata owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("artifact_metadata_id", "artifact_id"),
        metadata_fields=("lineage", "quality", "provenance", "schema_version"),
        relationships_in=("references",),
        relationships_out=("validates", "references"),
    ),
    _future_legend(
        "artifact_collection",
        owner_domain="data_manager",
        owner_component="future artifact collection owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("artifact_collection_id",),
        metadata_fields=("artifact_refs", "collection_policy"),
        relationships_out=("owns", "references"),
    ),
    _future_legend(
        "analysis_database",
        owner_domain="analysis",
        owner_component="future analysis database owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("analysis_database_id",),
        metadata_fields=("component_refs", "schema_ref", "materialization_state"),
        relationships_in=("builds_database",),
        relationships_out=("owns", "references"),
    ),
    _future_legend(
        "analysis_project",
        owner_domain="analysis",
        owner_component="future analysis project owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("analysis_project_id",),
        metadata_fields=("database_refs", "run_refs", "report_refs"),
        relationships_out=("owns", "builds_database", "produces_report"),
    ),
    _future_legend(
        "analysis_run",
        owner_domain="analysis",
        owner_component="future analysis run owner",
        runtime_or_persistent="hybrid",
        required_identity_fields=("analysis_run_id",),
        metadata_fields=("project_ref", "input_refs", "status", "result_refs"),
        relationships_in=("creates_operation",),
        relationships_out=("produces_report", "validates", "references"),
    ),
    _future_legend(
        "analysis_report",
        owner_domain="analysis",
        owner_component="future analysis report owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("analysis_report_id",),
        metadata_fields=("run_ref", "artifact_refs", "summary"),
        relationships_in=("produces_report",),
        relationships_out=("references",),
    ),
    _future_legend(
        "saved_rule_package",
        owner_domain="analysis",
        owner_component="future rule package owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("rule_package_id",),
        metadata_fields=("rule_refs", "validation_refs", "version"),
        relationships_out=("validates", "references"),
    ),
    _future_legend(
        "validation_scenario",
        owner_domain="analysis",
        owner_component="future validation scenario owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("validation_scenario_id",),
        metadata_fields=("input_refs", "expected_outcomes", "rule_package_refs"),
        relationships_in=("validates",),
        relationships_out=("validates", "references"),
    ),
    _future_legend(
        "trading_signal",
        owner_domain="trading",
        owner_component="future trading signal owner",
        runtime_or_persistent="hybrid",
        required_identity_fields=("trading_signal_id",),
        metadata_fields=("strategy_ref", "market_ref", "signal_state"),
        relationships_in=("produces_artifact",),
        relationships_out=("references",),
    ),
    _future_legend(
        "trading_strategy",
        owner_domain="trading",
        owner_component="future trading strategy owner",
        runtime_or_persistent="persistent",
        required_identity_fields=("trading_strategy_id",),
        metadata_fields=("signal_refs", "risk_policy_refs", "version"),
        relationships_out=("owns", "references"),
    ),
    _future_legend(
        "order_intent",
        owner_domain="trading",
        owner_component="future order intent owner",
        runtime_or_persistent="runtime",
        required_identity_fields=("order_intent_id",),
        metadata_fields=("strategy_ref", "market_ref", "side", "quantity_policy"),
        relationships_in=("triggers",),
        relationships_out=("references",),
    ),
    _future_legend(
        "provider_session",
        owner_domain="provider",
        owner_component="future provider session owner",
        runtime_or_persistent="runtime",
        required_identity_fields=("provider_session_id",),
        metadata_fields=("provider", "connection_refs", "capability_refs"),
        relationships_in=("uses_connection",),
        relationships_out=("uses_connection", "owns_channel", "references"),
    ),
    _future_legend(
        "websocket_subscription",
        owner_domain="core.connection",
        owner_component="future websocket subscription owner",
        runtime_or_persistent="runtime",
        required_identity_fields=("subscription_id", "channel_id"),
        metadata_fields=("topic", "market_ref", "status"),
        relationships_in=("owns",),
        relationships_out=("references",),
    ),
    _future_legend(
        "websocket_message_trace",
        owner_domain="core.connection",
        owner_component="future websocket message trace owner",
        runtime_or_persistent="temporary",
        required_identity_fields=("message_trace_id", "channel_id"),
        metadata_fields=("direction", "message_type", "timestamp_utc"),
        relationships_in=("references",),
        relationships_out=("references",),
    ),
)

_LEGENDS_BY_ID = MappingProxyType(
    {legend.family_id: legend for legend in OBJECT_FAMILY_LEGENDS}
)
_LEGENDS_BY_KIND = MappingProxyType(
    {legend.object_kind: legend for legend in OBJECT_FAMILY_LEGENDS}
)


def all_object_family_legends() -> tuple[ObjectFamilyLegend, ...]:
    """Return all static object family legends in deterministic order."""

    return OBJECT_FAMILY_LEGENDS


def object_family_legend_by_id(family_id: str) -> ObjectFamilyLegend | None:
    """Return a static family legend by family identifier."""

    _validate_lookup_key(family_id, "family_id")
    return _LEGENDS_BY_ID.get(family_id)


def object_family_legend_by_kind(object_kind: str) -> ObjectFamilyLegend | None:
    """Return a static family legend by object kind."""

    _validate_lookup_key(object_kind, "object_kind")
    return _LEGENDS_BY_KIND.get(object_kind)


def _validate_lookup_key(value: str, field_name: str) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field_name} must be a non-empty string")


def _validate_unique_legends() -> None:
    if len(_LEGENDS_BY_ID) != len(OBJECT_FAMILY_LEGENDS):
        raise ValueError("Duplicate object family legend family_id")
    if len(_LEGENDS_BY_KIND) != len(OBJECT_FAMILY_LEGENDS):
        raise ValueError("Duplicate object family legend object_kind")


_validate_unique_legends()

__all__ = [
    "CURRENT_V2_FAMILY_IDS",
    "FUTURE_PLACEHOLDER_FAMILY_IDS",
    "OBJECT_FAMILY_LEGENDS",
    "all_object_family_legends",
    "object_family_legend_by_id",
    "object_family_legend_by_kind",
]
