from leonardo.contracts.identity import Permission


def test_permission_matrix_has_stable_canonical_values() -> None:
    expected_values = {
        Permission.RUNTIME_VIEW: "runtime:view",
        Permission.RUNTIME_MANAGE: "runtime:manage",
        Permission.AUDIT_VIEW: "audit:view",
        Permission.SERVICE_VIEW: "service:view",
        Permission.SERVICE_MANAGE: "service:manage",
        Permission.ERROR_VIEW: "error:view",
        Permission.TASK_VIEW: "task:view",
        Permission.TASK_MANAGE: "task:manage",
        Permission.OPERATION_VIEW: "operation:view",
        Permission.OPERATION_MANAGE: "operation:manage",
        Permission.PROCESS_VIEW: "process:view",
        Permission.PROCESS_MANAGE: "process:manage",
        Permission.CONNECTION_VIEW: "connection:view",
        Permission.CONNECTION_MANAGE: "connection:manage",
        Permission.SETTINGS_VIEW: "settings:view",
        Permission.SETTINGS_MANAGE: "settings:manage",
        Permission.DOWNLOAD_VIEW: "download:view",
        Permission.DOWNLOAD_PREVIEW: "download:preview",
        Permission.DOWNLOAD_SUBMIT: "download:submit",
        Permission.DOWNLOAD_EXECUTE: "download:execute",
        Permission.DOWNLOAD_CANCEL: "download:cancel",
        Permission.DOWNLOAD_MANAGE: "download:manage",
        Permission.RESEARCH_VIEW: "research:view",
        Permission.RESEARCH_RUN: "research:run",
        Permission.RESEARCH_SAVE: "research:save",
        Permission.RESEARCH_MANAGE: "research:manage",
        Permission.DATA_MANAGER_VIEW: "data_manager:view",
        Permission.DATA_MANAGER_CALCULATE: "data_manager:calculate",
        Permission.DATA_MANAGER_MATERIALIZE: "data_manager:materialize",
        Permission.DATA_MANAGER_UPDATE: "data_manager:update",
        Permission.DATA_MANAGER_DELETE: "data_manager:delete",
        Permission.DATA_MANAGER_MANAGE: "data_manager:manage",
        Permission.ANALYSIS_VIEW: "analysis:view",
        Permission.ANALYSIS_RUN: "analysis:run",
        Permission.ANALYSIS_SAVE: "analysis:save",
        Permission.ANALYSIS_DELETE: "analysis:delete",
        Permission.ANALYSIS_MANAGE: "analysis:manage",
        Permission.TRADING_VIEW: "trading:view",
        Permission.TRADING_SIMULATE: "trading:simulate",
        Permission.TRADING_EXECUTE: "trading:execute",
        Permission.TRADING_CANCEL: "trading:cancel",
        Permission.TRADING_MANAGE: "trading:manage",
        Permission.CONNECTION_CONNECT: "connection:connect",
        Permission.CONNECTION_DISCONNECT: "connection:disconnect",
        Permission.CONNECTION_SUBSCRIBE: "connection:subscribe",
        Permission.GUI_SETTINGS_MANAGE: "gui_settings:manage",
    }

    assert {permission: permission.value for permission in Permission} == expected_values
    assert len({permission.value for permission in Permission}) == len(Permission)
