"""Research Area read models and application services."""

from leonardo.research.application import ResearchDatasetApplicationService
from leonardo.research.catalog import (
    AcceptedDatasetCatalog,
    AcceptedDatasetSummary,
    DatasetCatalogReport,
    DatasetRejection,
)
from leonardo.research.dataset import (
    DatasetNotAcceptedError,
    HistoricalDataset,
    HistoricalDatasetLoadCancelled,
    HistoricalDatasetLoadError,
    HistoricalDatasetLoader,
)
from leonardo.research.viewport import (
    DEFAULT_LEFT_PADDING,
    DEFAULT_REFILL_THRESHOLD,
    DEFAULT_RIGHT_PADDING,
    DEFAULT_VISIBLE_BARS,
    MAX_VISIBLE_BARS,
    MIN_VISIBLE_BARS,
    DatasetInterest,
    HorizontalViewport,
    ResidentRefillDirection,
    ViewportSnapshot,
)
from leonardo.research.session import (
    ChartSessionDisposedError,
    ChartSessionState,
    ChartSessionStateError,
)
from leonardo.research.resident import (
    DEFAULT_BUFFER_LEFT,
    DEFAULT_BUFFER_RIGHT,
    DEFAULT_RESIDENT_TARGET,
    DEFAULT_VISIBLE_MAX,
    ResidentOHLCVSlice,
    ResidentSliceService,
)
from leonardo.research.studies import (
    ChartStudy,
    ChartStudyRegistry,
    PreparedStudy,
    StudyApplyAttempt,
    StudyArtifactRequest,
    StudyDependencyError,
    StudyDependencyRef,
    StudyError,
    StudyExecutionRequest,
    StudyInputSource,
    StudyNotFoundError,
    StudyOperationCancelled,
    StudySaveAttempt,
    StudySaveBlockedError,
    StudySaveOutcome,
    StudySavedLink,
    StudyValidationError,
)
from leonardo.research.study_application import ResearchStudyApplicationService
from leonardo.research.study_execution import ResearchStudyService
from leonardo.research.study_projection import ResidentStudyProjection
from leonardo.research.study_presentation import (
    StudyFillStyle,
    StudyLineStyle,
    StudyManagerEntry,
    StudyPresentation,
    StudyPresentationRegistry,
    StudyPresentationValidationError,
    build_default_study_presentation,
)

from leonardo.research.volume import (
    DEFAULT_VOLUME_MEAN_PERIOD,
    ResidentVolumeProjection,
    build_resident_volume_projection,
)

__all__ = [
    "build_resident_volume_projection",
    "ResidentVolumeProjection",
    "DEFAULT_VOLUME_MEAN_PERIOD",
    "DEFAULT_LEFT_PADDING",
    "DEFAULT_REFILL_THRESHOLD",
    "DEFAULT_RIGHT_PADDING",
    "DEFAULT_VISIBLE_BARS",
    "MAX_VISIBLE_BARS",
    "MIN_VISIBLE_BARS",
    "DatasetInterest",
    "HorizontalViewport",
    "ResidentRefillDirection",
    "ViewportSnapshot",
    "ChartSessionDisposedError",
    "ChartSessionState",
    "ChartSessionStateError",
    "DEFAULT_BUFFER_LEFT",
    "DEFAULT_BUFFER_RIGHT",
    "DEFAULT_RESIDENT_TARGET",
    "DEFAULT_VISIBLE_MAX",
    "ResidentOHLCVSlice",
    "ResidentSliceService",
    "AcceptedDatasetCatalog",
    "AcceptedDatasetSummary",
    "DatasetCatalogReport",
    "DatasetNotAcceptedError",
    "DatasetRejection",
    "HistoricalDataset",
    "HistoricalDatasetLoadCancelled",
    "HistoricalDatasetLoadError",
    "HistoricalDatasetLoader",
    "ResearchDatasetApplicationService",
    "ChartStudy",
    "ChartStudyRegistry",
    "PreparedStudy",
    "ResearchStudyApplicationService",
    "ResearchStudyService",
    "ResidentStudyProjection",
    "StudyApplyAttempt",
    "StudyArtifactRequest",
    "StudyDependencyError",
    "StudyDependencyRef",
    "StudyError",
    "StudyExecutionRequest",
    "StudyInputSource",
    "StudyNotFoundError",
    "StudyOperationCancelled",
    "StudySaveAttempt",
    "StudySaveBlockedError",
    "StudySaveOutcome",
    "StudySavedLink",
    "StudyValidationError",
    "StudyFillStyle",
    "StudyLineStyle",
    "StudyManagerEntry",
    "StudyPresentation",
    "StudyPresentationRegistry",
    "StudyPresentationValidationError",
    "build_default_study_presentation",
]
